apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "plugin-bench.workloadRoleName" . }}
  namespace: {{ include "plugin-bench.workloadNamespace" . | quote }}
  labels:
    {{- include "plugin-bench.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "delete"]
