apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "plugin-bench.coordinatorServiceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "plugin-bench.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "plugin-bench.runnerServiceAccountName" . }}
  namespace: {{ include "plugin-bench.workloadNamespace" . | quote }}
  labels:
    {{- include "plugin-bench.labels" . | nindent 4 }}
automountServiceAccountToken: false
